services:
  securitycam:
    container_name: securitycam_container
    image: securitycam:v1.0
    restart: always
    ports:
      - "8069:8069"
    volumes:
      - type: bind
        source: /home/nico/sambashare/securitycam/logs
        target: /usr/src/app/logs
      - type: bind
        source: /home/nico/sambashare/securitycam/camera_confs
        target: /usr/src/app/camera_confs
      - type: bind
        source: /home/nico/sambashare/securitycam/pictures
        target: /usr/src/app/pictures