services:
  housedashboard:
    container_name: housedashboard_container
    image: house_dashboard:v0.2
    restart: always
    ports:
      - "8069:8069"
    volumes:
      - type: bind
        source: /home/nico/sambashare/housedashboard/logs
        target: /usr/src/app/logs
      - type: bind
        source: /home/nico/sambashare/housedashboard/config
        target: /usr/src/app/config